:output:
  User:
    :options:
      :fields:
      - id
      - username
      - email
      - first_name
      - last_name
      - admin?
      - author?
  Post:
    :options:
      :fields:
      - id
      - user_id
      - title
      - position
  Bill:
    :options:
      :fields:
      - full_number
      - title
      - last_action_on
      - state
      - ignored?